param(
  [string]$WorkspaceRoot = (Get-Location).Path
)

$ErrorActionPreference = 'Stop'

function New-CleanDirectory {
  param([string]$Path)

  if (Test-Path $Path) {
    Remove-Item -Recurse -Force $Path
  }
  New-Item -ItemType Directory -Path $Path | Out-Null
}

$srcRoot = Join-Path $WorkspaceRoot 'src'
$frontSrc = Join-Path $srcRoot 'front'
$backSrc = Join-Path $srcRoot 'back'

if (-not (Test-Path $frontSrc) -or -not (Test-Path $backSrc)) {
  throw "Khong tim thay cau truc src/front va src/back tai: $srcRoot"
}

$submissionRoot = Join-Path $WorkspaceRoot 'submission'
$sourceRoot = Join-Path $submissionRoot 'source'
$frontOut = Join-Path $sourceRoot 'front'
$backOut = Join-Path $sourceRoot 'back'

New-CleanDirectory -Path $sourceRoot
New-Item -ItemType Directory -Path $frontOut | Out-Null
New-Item -ItemType Directory -Path $backOut | Out-Null

Write-Host '[1/4] Copy frontend source...' -ForegroundColor Cyan
robocopy $frontSrc $frontOut /E /NFL /NDL /NJH /NJS /NP /XD node_modules dist test-results .git
if ($LASTEXITCODE -ge 8) { throw "Robocopy frontend that bai (exit code $LASTEXITCODE)" }

Write-Host '[2/4] Copy backend source...' -ForegroundColor Cyan
robocopy $backSrc $backOut /E /NFL /NDL /NJH /NJS /NP /XD node_modules uploads .git
if ($LASTEXITCODE -ge 8) { throw "Robocopy backend that bai (exit code $LASTEXITCODE)" }

Write-Host '[3/4] Remove runtime artifacts...' -ForegroundColor Cyan
Get-ChildItem -Path $backOut -Recurse -Include *.pid,*.log,*.err,*.out -File -ErrorAction SilentlyContinue |
  Remove-Item -Force -ErrorAction SilentlyContinue

Write-Host '[4/4] Write manifest...' -ForegroundColor Cyan
$manifestPath = Join-Path $sourceRoot 'SUBMISSION_MANIFEST.txt'
@(
  'Submission package generated by scripts/ops/prepare_submission_source.ps1',
  "GeneratedAt: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
  '',
  'Included:',
  '- source/front (frontend source + config)',
  '- source/back (backend source + prisma + scripts + config)',
  '',
  'Excluded:',
  '- node_modules, dist, test-results, uploads',
  '- runtime logs/pid artifacts'
) | Set-Content -Path $manifestPath -Encoding UTF8

Write-Host "Done. Submission source is ready at: $sourceRoot" -ForegroundColor Green
